const env = {
    STRAPI_API_KEY: process.env.NEXT_PUBLIC_STRAPI_API_KEY,
    STRAPI_SERVER_URL: process.env.NEXT_PUBLIC_STRAPI_SERVER_URL,
    FALLBACK_IMAGE_URL: process.env.NEXT_PUBLIC_FALLBACK_IMAGE_URL,
    PLACEHOLDER_IMAGE_URL: process.env.NEXT_PUBLIC_PLACEHOLDER_IMAGE_URL,
    LOGO_IMAGE_URL: process.env.NEXT_PUBLIC_LOGO_IMAGE_URL,
    LOGO_IMAGE_ALT: process.env.NEXT_PUBLIC_LOGO_IMAGE_ALT,
}

export default env;